---
- name: www/Install nginx
  action: yum pkg=nginx state=latest
  tags:
    - packages
    - bootstrap
- name: www/Configure nginx
  action: template src=nginx.conf dest=/etc/nginx/nginx.conf
  tags:
    - reconfigure
  notify:
    - nginx-reload
- name: www/Enable nginx
  action: service name=nginx state=reloaded enabled=true
  tags:
    - services
    - bootstrap
